### ISSUE TITLE
Luminance crash game

### ISSUE THREAD

**Issue by BrotKrip** [DominicKarma/Luminance#49]
[21:35:13.991] [.NET TP Worker/ERROR] [tML]: Unhandled Exception
System.ArgumentException: An item with the same key has already been added. Key: {710, 208}
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at Terraria.Lighting.AddLight(Int32 i, Int32 j, Single r, Single g, Single b) in tModLoader\Terraria\Lighting.cs:line 175
   at NoxusBoss.Content.Particles.StrongBloom.Update() in NoxusBoss\Content\Particles\StrongBloom.cs:line 27
   at Luminance.Core.Graphics.ParticleManager.<>c.<PostUpdateDusts>b__8_0(Int32 x, Int32 y, Object context) in Luminance\Core\Graphics\Particles\ParticleManager.cs:line 50
   at ReLogic.Threading.FastParallel.RangeTask.Invoke() in D:\a\tModLoader\tModLoader\src\tModLoader\ReLogic\Threading\FastParallel.cs:line 37
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()

**Comment by BrotKrip** [comment]
And another one:

[22:27:05.729] [.NET TP Worker/ERROR] [tML]: Unhandled Exception
System.ArgumentException: An item with the same key has already been added. Key: {990, 258}
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at Terraria.Lighting.AddLight(Int32 i, Int32 j, Single r, Single g, Single b) in tModLoader\Terraria\Lighting.cs:line 175
   at NoxusBoss.Content.Particles.StrongBloom.Update() in NoxusBoss\Content\Particles\StrongBloom.cs:line 27
   at Luminance.Core.Graphics.ParticleManager.<>c.<PostUpdateDusts>b__8_0(Int32 x, Int32 y, Object context) in Luminance\Core\Graphics\Particles\ParticleManager.cs:line 50
   at ReLogic.Threading.FastParallel.RangeTask.Invoke() in D:\a\tModLoader\tModLoader\src\tModLoader\ReLogic\Threading\FastParallel.cs:line 37
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
