### ISSUE TITLE
Luminance is crashing my game

### ISSUE THREAD

**Issue by PLMMJ-FH** [DominicKarma/Luminance#54]
I have Luminance on, and the game crashed when it tried to finish loading. I didn't remember to copy the crash message but it only mentioned directories referring to Terraria, Microsoft, and Luminance.

**Comment by PLMMJ-FH** [comment]
It crashed again, I checked the log file and this is the error message:

Main engine crash

Tip: This is likely a mod's fault. Disable mods one by one and check if the issue persists

System.InvalidOperationException: Texture2D creation failed! Error Code: Not enough memory resources are available to complete this operation. (0x8007000E)
   at Microsoft.Xna.Framework.FNALoggerEXT.FNA3DLogError(IntPtr msg) in D:\a\tModLoader\tModLoader\FNA\src\FNALoggerEXT.cs:line 98
   at Microsoft.Xna.Framework.Graphics.FNA3D_Impl.FNA3D_CreateTexture2D(IntPtr device, SurfaceFormat format, Int32 width, Int32 height, Int32 levelCount, Byte isRenderTarget)
   at Microsoft.Xna.Framework.Graphics.Texture2D..ctor(GraphicsDevice graphicsDevice, Int32 width, Int32 height, Boolean mipMap, SurfaceFormat format) in D:\a\tModLoader\tModLoader\FNA\src\Graphics\Texture2D.cs:line 116
   at Microsoft.Xna.Framework.Graphics.RenderTarget2D..ctor(GraphicsDevice graphicsDevice, Int32 width, Int32 height, Boolean mipMap, SurfaceFormat preferredFormat, DepthFormat preferredDepthFormat, Int32 preferredMultiSampleCount, RenderTargetUsage usage) in D:\a\tModLoader\tModLoader\FNA\src\Graphics\RenderTarget2D.cs:line 132
   at Microsoft.Xna.Framework.Graphics.RenderTarget2D..ctor(GraphicsDevice graphicsDevice, Int32 width, Int32 height) in D:\a\tModLoader\tModLoader\FNA\src\Graphics\RenderTarget2D.cs:line 92
   at Luminance.Core.Graphics.PrimitivePixelationSystem.CreatePixelTarget(Int32 width, Int32 height) in Luminance\Core\Graphics\Primitives\PrimitivePixelationSystem.cs:line 25
   at Luminance.Core.Graphics.ManagedRenderTarget.Recreate(Int32 screenWidth, Int32 screenHeight) in Luminance\Core\Graphics\Automators\ManagedRenderTarget.cs:line 148
   at Luminance.Core.Graphics.RenderTargetManager.<>c__DisplayClass10_0.<PerformTargetResetCheck>b__0() in Luminance\Core\Graphics\Automators\RenderTargetManager.cs:line 107
   at Terraria.Main.ConsumeAllMainThreadActions() in tModLoader\Terraria\Main.cs:line 14130
   at Terraria.Main.Update(GameTime gameTime) in tModLoader\Terraria\Main.cs:line 14168
   at Microsoft.Xna.Framework.Game.Tick() in D:\a\tModLoader\tModLoader\FNA\src\Game.cs:line 546
   at Microsoft.Xna.Framework.Game.RunLoop() in D:\a\tModLoader\tModLoader\FNA\src\Game.cs:line 878
   at Microsoft.Xna.Framework.Game.Run() in D:\a\tModLoader\tModLoader\FNA\src\Game.cs:line 419
   at Terraria.Program.RunGame() in tModLoader\Terraria\Program.cs:line 266

**Comment by PLMMJ-FH** [comment]
Oh. My computer memory is not enough apparently. It was okay up until the update yesterday.

System.InvalidOperationException: Texture2D creation failed! Error Code: Not enough memory resources are available to complete this operation. (0x8007000E)
